image: python:3.10
tasks:
  - init: |
      pip install -r requirements.txt
      pip install --use-feature=in-tree-build --editable .
ports:
  - port: 9000
    onOpen: ignore
vscode:
  extensions:
    - ms-python.python
